<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CarBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('car_brands')->insert([
            [
                "name"=>"Agrale",
                "image"=>"data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/7QCcUGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAIAcAigAYkZCTUQwMTAwMGFjMzAzMDAwMGI0MGMwMDAwNTQxNTAwMDBhYjE3MDAwMGVmMTkwMDAwNWQyMDAwMDA3ZTJiMDAwMDJhMmUwMDAwNTYzMDAwMDBiYzMyMDAwMDRkNDgwMDAwHAJnABRJUlR0LWpWNHlIcVJiYy1B",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Alfa Romeo",
                "image"=>"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAAAAADRE4smAAAtXUlEQVR42u2d918UxxvHv3/OHEc5RCyggg0LKsQoarBgIxpjDBZMYopYo9iwYC/EiERRgwUbGjtqbNhQQSM2LGdD5BQO5vu6vn1n93bvFub5/AR7uzN787xvd+aZZ575HwJRrf9BEwAAIAAABACAAAAQAAACAEAAAAgAAAEAIAAABACAAAAQAAACA",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"AMC",
                "image"=>"data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/7QCcUGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAIAcAigAYkZCTUQwMTAwMGFjMzAzMDAwMGI0MGMwMDAwNTQxNTAwMDBhYjE3MDAwMGVmMTkwMDAwNWQyMDAwMDA3ZTJiMDAwMDJhMmUwMDAwNTYzMDAwMDBiYzMyMDAwMDRkNDgwMDAwHAJnABRJUlR0LWpWNHlIcVJiYy1B",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"ARO",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Aston Martin",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Audi",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Autogago",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Bentley",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Bera",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"BMW",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Bugatti",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Buick",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"BYD",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Cadillac",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Calto",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Caterpillar",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Chana",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Changhe",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Chery",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Chevrolet",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Chrysler",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Cinascar",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Citroen",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Conquistador",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Cummings",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Dacia",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Daewoo",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Daihatsu",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Dodge",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Dongfeng",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"EBRO",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Encava",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Empire",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Ferrari",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Fiat",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Ford",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Foton",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Freightliner",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Geely",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"General Motors",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"GMC",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Great Wall",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Guri",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Hafei",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Haima",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Hino",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Honda",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Howo",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Hummer",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Hyundai",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Infiniti",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"International",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Isuzu",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Itarca",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Iveco",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"JAC",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Jaguar",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Jeep",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"JMC",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Kawasaki",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Kia",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Koenigsegg",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Lada",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Lamborghini",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Land Rover",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Lexus",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Lifan",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Mack",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Maserati",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"MAZ",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Mazda",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"McLaren",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Mercedes Benz",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Mercury",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Mini",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Minicooper",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Mitsubishi",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Moto",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Nissan",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"OPEL",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Pagani",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Pegaso",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Peugeot",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Pontiac",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Porsche",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Ram",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Renault",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Rolls Royce",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Rover",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Saab",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Saic Wuling",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Sangyong",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Sany",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Saturn",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Scania",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Seat",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Skoda",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Skygo",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Smart",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Subaru",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Suzuki",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Tata Motors",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Tesla",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Titan",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Toyota",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Venirauto",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Volkswagen",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Volvo",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Wuling",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Yamaha",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Yutong",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Zhongxing",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ],
            [
                "name"=>"Zotye",
                "image"=>"",
                "description"=>"Descripcion",
                "counter"=>0,
                "active"=>true
            ]
        ]);
    }
}
