@URL=http://127.0.0.1:8000/api
@TOKEN=Bearer 4|25SMACZteCJYD94YahVe7UoE4EVtibXpruRVrVdb


##############################################
GET {{ URL }}/carbrand/
Accept: application/json

##############################################
GET {{ URL }}/admin/brand/
Accept: application/json
Authorization: {{TOKEN}}

##############################################
