@URL=http://127.0.0.1:8000/api
@TOKEN=123123

##############################################
GET {{ URL }}/carbrand/
Accept: application/json


##############################################
GET {{ URL }}/carmodel/1
Accept: application/json
