@URL=http://127.0.0.1:8000/api
@TOKEN=123123

##############################################
POST {{ URL }}/register/
Accept: application/json
Content-Type: application/json

{
    "name": "David",
    "email": "saotand@gmail.com",
    "password": "d0708aca"
}


##############################################
POST {{ URL }}/login/
Accept: application/json
Content-Type: application/json

{
    "email":"saotand@gmail.com",
    "password":"d0708aca"
}
